//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hespress_application.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="News_Links", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class News_Links : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActualiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LienField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Actualite {
            get {
                return this.ActualiteField;
            }
            set {
                if ((object.ReferenceEquals(this.ActualiteField, value) != true)) {
                    this.ActualiteField = value;
                    this.RaisePropertyChanged("Actualite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Lien {
            get {
                return this.LienField;
            }
            set {
                if ((object.ReferenceEquals(this.LienField, value) != true)) {
                    this.LienField = value;
                    this.RaisePropertyChanged("Lien");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name getNewsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNews", ReplyAction="*")]
        Hespress_application.ServiceReference1.getNewsResponse getNews(Hespress_application.ServiceReference1.getNewsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getNews", ReplyAction="*")]
        System.Threading.Tasks.Task<Hespress_application.ServiceReference1.getNewsResponse> getNewsAsync(Hespress_application.ServiceReference1.getNewsRequest request);
        
        // CODEGEN: Generating message contract since element name title from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfos", ReplyAction="*")]
        Hespress_application.ServiceReference1.getInfosResponse getInfos(Hespress_application.ServiceReference1.getInfosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getInfos", ReplyAction="*")]
        System.Threading.Tasks.Task<Hespress_application.ServiceReference1.getInfosResponse> getInfosAsync(Hespress_application.ServiceReference1.getInfosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNews", Namespace="http://tempuri.org/", Order=0)]
        public Hespress_application.ServiceReference1.getNewsRequestBody Body;
        
        public getNewsRequest() {
        }
        
        public getNewsRequest(Hespress_application.ServiceReference1.getNewsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getNewsRequestBody {
        
        public getNewsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getNewsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getNewsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hespress_application.ServiceReference1.getNewsResponseBody Body;
        
        public getNewsResponse() {
        }
        
        public getNewsResponse(Hespress_application.ServiceReference1.getNewsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getNewsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hespress_application.ServiceReference1.News_Links[] getNewsResult;
        
        public getNewsResponseBody() {
        }
        
        public getNewsResponseBody(Hespress_application.ServiceReference1.News_Links[] getNewsResult) {
            this.getNewsResult = getNewsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfos", Namespace="http://tempuri.org/", Order=0)]
        public Hespress_application.ServiceReference1.getInfosRequestBody Body;
        
        public getInfosRequest() {
        }
        
        public getInfosRequest(Hespress_application.ServiceReference1.getInfosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public getInfosRequestBody() {
        }
        
        public getInfosRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInfosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getInfosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Hespress_application.ServiceReference1.getInfosResponseBody Body;
        
        public getInfosResponse() {
        }
        
        public getInfosResponse(Hespress_application.ServiceReference1.getInfosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getInfosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Hespress_application.ServiceReference1.ArrayOfString getInfosResult;
        
        public getInfosResponseBody() {
        }
        
        public getInfosResponseBody(Hespress_application.ServiceReference1.ArrayOfString getInfosResult) {
            this.getInfosResult = getInfosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Hespress_application.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Hespress_application.ServiceReference1.WebServiceSoap>, Hespress_application.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hespress_application.ServiceReference1.getNewsResponse Hespress_application.ServiceReference1.WebServiceSoap.getNews(Hespress_application.ServiceReference1.getNewsRequest request) {
            return base.Channel.getNews(request);
        }
        
        public Hespress_application.ServiceReference1.News_Links[] getNews() {
            Hespress_application.ServiceReference1.getNewsRequest inValue = new Hespress_application.ServiceReference1.getNewsRequest();
            inValue.Body = new Hespress_application.ServiceReference1.getNewsRequestBody();
            Hespress_application.ServiceReference1.getNewsResponse retVal = ((Hespress_application.ServiceReference1.WebServiceSoap)(this)).getNews(inValue);
            return retVal.Body.getNewsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hespress_application.ServiceReference1.getNewsResponse> Hespress_application.ServiceReference1.WebServiceSoap.getNewsAsync(Hespress_application.ServiceReference1.getNewsRequest request) {
            return base.Channel.getNewsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hespress_application.ServiceReference1.getNewsResponse> getNewsAsync() {
            Hespress_application.ServiceReference1.getNewsRequest inValue = new Hespress_application.ServiceReference1.getNewsRequest();
            inValue.Body = new Hespress_application.ServiceReference1.getNewsRequestBody();
            return ((Hespress_application.ServiceReference1.WebServiceSoap)(this)).getNewsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Hespress_application.ServiceReference1.getInfosResponse Hespress_application.ServiceReference1.WebServiceSoap.getInfos(Hespress_application.ServiceReference1.getInfosRequest request) {
            return base.Channel.getInfos(request);
        }
        
        public Hespress_application.ServiceReference1.ArrayOfString getInfos(string title) {
            Hespress_application.ServiceReference1.getInfosRequest inValue = new Hespress_application.ServiceReference1.getInfosRequest();
            inValue.Body = new Hespress_application.ServiceReference1.getInfosRequestBody();
            inValue.Body.title = title;
            Hespress_application.ServiceReference1.getInfosResponse retVal = ((Hespress_application.ServiceReference1.WebServiceSoap)(this)).getInfos(inValue);
            return retVal.Body.getInfosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Hespress_application.ServiceReference1.getInfosResponse> Hespress_application.ServiceReference1.WebServiceSoap.getInfosAsync(Hespress_application.ServiceReference1.getInfosRequest request) {
            return base.Channel.getInfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Hespress_application.ServiceReference1.getInfosResponse> getInfosAsync(string title) {
            Hespress_application.ServiceReference1.getInfosRequest inValue = new Hespress_application.ServiceReference1.getInfosRequest();
            inValue.Body = new Hespress_application.ServiceReference1.getInfosRequestBody();
            inValue.Body.title = title;
            return ((Hespress_application.ServiceReference1.WebServiceSoap)(this)).getInfosAsync(inValue);
        }
    }
}
